name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: |
        yarn
        ls -al ./node_modules/eslint/bin
    - name: Lint
      run: ./node_modules/eslint/bin/eslint .
