name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install modules
      run: yarn --prod=false
    - name: Lint
      run: yarn run eslint .
    - name: Test
      run: npm test
