name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install modules
      run: |
        mkdir ../pyramid
        wget -P ../pyramid https://beakerboy.github.io/Threejs-Geometries/src/PyramidGeometry.js
        cd ../pyramid
        echo '{"name":"pyramid","license":"UNLICENSED","private":true,"scripts":{"test":"npx jest"}}' > "./package.json" && npm init -y
        npm install
        cd ../OSMBuilding
        yarn --prod=false
    - name: Lint
      run: yarn run eslint .
    - name: Test
      run: CI=true NODE_OPTIONS="$NODE_OPTIONS --experimental-vm-modules" npm test
    - name: Coveralls
      uses: coverallsapp/github-action@v2
